### ISSUE TITLE
WTF，It's couldn't update data

### ISSUE THREAD

**Issue by webliupeng** [open-node/open-rest#3]
There is no any error or log while I update a entity by helper.rest.update without specify field in model's editable.  I hope that output some warning information for these situation

**Comment by garbin** [comment]
@webliupeng Silly B, SB for short!!!

**Comment by bilxio** [comment]
Hi there, could you just post more detail informations about your issue please? 

```
Open-Rest Version: X.X.X
Node Version: X.X.X
```

**Comment by webliupeng** [comment]
@bilxio 伐克油
